### ISSUE TITLE
ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by driquelme** [bitcartcc/bitcart-docker#21]
Hello!

I'm having trouble connecting to the admin and store pages using docker.
I followed the instructions and did the following:
- Setup dns entries 
- exported the corresponding variables
-- Used: `export BITCART_REVERSEPROXY=none` (Used socat for port forwarding)
- Ran ./setup.sh as a regular user
- Ran ./start.sh as root

When I connect to the admin or store websites I get the following error in the stdout of the docker container:

```
 ERROR  connect ECONNREFUSED 127.0.0.1:80

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

The api page displays the api as expected.

If I use `export BITCART_REVERSEPROXY=nginx`, I get the following errors in the console:

```
nginx-gen                            | 2021/11/26 11:43:35 Received event die for container 331b2f71c92e
nginx-gen                            | 2021/11/26 11:43:37 Received signal: hangup
nginx-gen                            | 2021/11/26 11:43:37 Received signal: hangup


dramatiq_1                           | python3: can't open file 'manage.py': [Errno 2] No such file or directory

daemon_1                             | python3: can't open file 'daemon.py': [Errno 2] No such file or directory
 ```

I suspect I'm missing something, but I haven't been able to figure it out

Environment
OSX BigSur 11.5.2
Docker 20.10.8

Thank you :)

**Comment by MrNaif2018** [comment]
Hi! Thanks for detailed information. First of all setup and start sh should probably run under root user as it sets up necessary things like installing docker, fixes for broken system libraries, exporting variables to user env (via /etc/profile.d) and so on.
The logs display `dramatiq_1` container: it doesn't exist in BitcartCC for a year or so already, are you sure you have used the most recent version of it? daemon.py I think doesn't exist for 2 years already.

Also the error is expected when nginx is disabled: by default one-domain mode is used, but when you disable nginx it can't run multiple services under same domain, it doesn't have domains at all. 
But first of all try cleaning up all docker volumes,  containers and images, removing `bitcart-docker` directory and re-cloning again, and re-running the setup again

**Comment by MrNaif2018** [comment]
Hi! Did you try cleaning the environment and re-running setup? Any luck?

**Comment by MrNaif2018** [comment]
Closing as it i[s solved](https://t.me/bitcartcc/5862)
