### ISSUE TITLE
New features discussion

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-docker#8]
There are currently two features that are worth implementing:
<strike>The first is adding tor support by adding tor component to `generator/docker-components` directory. </strike>**Done**
The second is more complicated, but might attract users who want to host they node and still use bitcart.
Currently bitcart works via default electrum servers.
There should be an electrumx component(configurable for each coin, maybe in generator's main.py), which will run,
It should be allowed to run in a few different cases:
If node is already installed somewhere, only electrumx component is needed to connect to bitcoin or other coin's node.
If nothing is installed users can also install both coin node and electrumx for that.
If those components are enabled, bitcart should be configured to use only one server from component and not public ones.
But the default settings should be left the same.

**Comment by Nerd2201** [comment]
Hi there,
I'm a newbie to crypto currencys but I'm quite good with python so if you want to give me a basic intro I'll be happy to help you with coding

**Comment by MrNaif2018** [comment]
Thanks a lot! If you're good in python I recommend you to take a look at bitcart-sdk repo and main bitcart repo. Bitcart-docker is for docker integration. I have opened a few issues, feel free to ask any questions in issues or in our telegram group!

**Comment by MrNaif2018** [comment]
It was decided that allowing to run fullnode will not be built-in in BitcartCC to keep things simple and to not limit users in how they configure their node
